name: braintree_web_example
description: Braintree/Paypal payment integration plugin example
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  braintree_web:
    path: ../
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
